### ISSUE TITLE
Panic in dubb writer after close: nil dereference

### ISSUE THREAD

**Issue by nilium** [nilium/dagr#3]
Unsure yet what's causing this. Need to look into it, but appears to happen after closing, which should be a nop instead of dereferencing nil.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x107378]

goroutine 1 [running]:
panic(0x1dd0e0, 0xc82000c120)
        /usr/local/Cellar/go/tip/src/runtime/panic.go:500 +0x18c
go.spiff.io/dagr/outflux/internal/dubb.(*Buffer).writer(0x0, 0x253c8780b31)
        /Users/ncower/go/src/go.spiff.io/dagr/outflux/internal/dubb/buffer.go:236 +0x18
go.spiff.io/dagr/outflux/internal/dubb.(*Buffer).Write(0x0, 0xc820111e1d, 0x0, 0xffe3, 0xc820111da8, 0xe901, 0x725230)
        /Users/ncower/go/src/go.spiff.io/dagr/outflux/internal/dubb/buffer.go:253 +0x21
go.spiff.io/dagr/outflux.(*Proxy).Write(0xc8200127d0, 0xc820111e1d, 0x0, 0xffe3, 0x1, 0x0, 0x2fe840)
        /Users/ncower/go/src/go.spiff.io/dagr/outflux/outflux.go:132 +0x47
main.(*porthole).Listen(0xc820010800, 0x2fe840, 0xc82019a0a0)
        /Users/ncower/go/src/go.spiff.io/janus/janus.go:111 +0x316
main.main()
        /Users/ncower/go/src/go.spiff.io/janus/janus.go:164 +0x1c3
```

**Comment by nilium** [comment]
dubb has been removed, but this is likely an error in the Proxy or Proxy usage. dubb just happened to be the thing to hit the nil deref first.
